---
# defaults file for nginx

nginx_upstreams:
- name: wordpress
  servers:
    - "192.168.50.20:80"
- name: gitlab
  servers:
    - "192.168.50.31:80"
- name: grafana
  servers:
    - "192.168.50.40:3000"
- name: prometheus
  servers:
    - "192.168.50.40:9090"
- name: alertmanager
  servers:
    - "192.168.50.40:9093"

nginx_vhosts:
- server_name: "www.groshev.site groshev.site"
  upstream: "wordpress"
- server_name: "gitlab.groshev.site"
  upstream: "gitlab"
- server_name: "grafana.groshev.site"
  upstream: "grafana"
- server_name: "prometheus.groshev.site"
  upstream: "prometheus"
- server_name: "alertmanager.groshev.site"
  upstream: "alertmanager"
