stages:     
  - deploy

before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")

deploy-job: 
  stage: deploy 
  only:
    - tags
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - ssh -o StrictHostKeyChecking=no root@192.168.50.20 "cd /var/www/wordpress && git checkout master && git pull origin master && exit"

