---
# tasks file for node_exporter
  - name: Create the node_exporter group
    group:
      name: "node_exporter"
      state: present
      system: true

  - name: Create the node_exporter user
    user:
      name: "node_exporter"
      groups: "node_exporter"
      append: true
      shell: /usr/sbin/nologin
      system: true
      create_home: false
      home: /home

  - name: Download node_exporter
    get_url:
      url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
      dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
      mode: 0755
      timeout: 60
      force: true
      validate_certs: false
    register: get_node_exporter
    until: get_node_exporter is succeeded

  - name: Create directrory for node_exporter
    file:
      state: directory
      path: "{{ node_exporter_home }}"

  - name: Extract node_exporter
    unarchive:
      copy: false
      src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
      dest: "{{ node_exporter_home }}"
      extra_opts: [--strip-components=1]

  - name: Copy the node_exporter systemd service file
    template:
      src: node_exporter.service.j2
      dest: /etc/systemd/system/node_exporter.service
      owner: root
      group: root
      mode: 0644
    notify: restart node_exporter
