---
#Install Grafana
#https://nc.lpec.ru/s/zANHzsXnEeyajdn/download/grafana-enterprise-9.1.6.linux-amd64.tar.gz
- name: Download grafana
  get_url:
    url: "https://nc.lpec.ru/s/zANHzsXnEeyajdn/download/grafana-enterprise-9.1.6.linux-amd64.tar.gz"
    dest: "/tmp/grafana.linux-amd64.tar.gz"
    mode: 0755
    timeout: 60
    force: true
    validate_certs: false
  register: get_alertm
  until: get_alertm is succeeded

- name: Create directrory for grafana
  file:
    owner: prometheus
    group: prometheus
    state: directory
    path: "{{ grafana_home }}"

- name: Extract grafana
  unarchive:
    owner: prometheus
    group: prometheus
    copy: false
    src: "/tmp/grafana.linux-amd64.tar.gz"
    dest: "{{ grafana_home }}"
    extra_opts: [--strip-components=1]

- name: Copy Grafana datasources
  copy:
    src: prometheus.yaml
    dest: "{{ grafana_home }}/conf/provisioning/datasources/prometheus.yaml"
    owner: prometheus
    group: prometheus

- name: Copy Grafana dashboards conf
  copy:
    src: sample.yaml
    dest: "{{ grafana_home }}/conf/provisioning/dashboards/sample.yaml"
    owner: prometheus
    group: prometheus

- name: Copy Grafana dashboards
  copy:
    src: Netology.json
    dest: "{{ grafana_home }}/conf/provisioning/dashboards/Netology.json"
    owner: prometheus
    group: prometheus

- name: Copy Grafana systemd service file
  template:
    src: grafana.service.j2
    dest: /etc/systemd/system/grafana.service
    owner: root
    group: root
    mode: 0644
  notify: restart grafana
