---
#Install prometheus
- name: Download prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    mode: 0755
    timeout: 60
    force: true
    validate_certs: false
  register: get_prometheus
  until: get_prometheus is succeeded

- name: Create directrory for prometheus
  file:
    owner: prometheus
    group: prometheus
    state: directory
    path: "{{ prometheus_home }}"

- name: Create config directrory for prometheus
  file:
    state: directory
    path: "/etc/prometheus"


- name: Extract prometheus
  unarchive:
    owner: prometheus
    group: prometheus
    copy: false
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "{{ prometheus_home }}"
    extra_opts: [--strip-components=1]
#      creates: "{{ elastic_home }}/bin/elasticsearch"

#  - name: Set environment Elastic
#    become: yes
#    template:
#      src: templates/elk.sh.j2
#      dest: /etc/profile.d/elk.sh
#    tags: elastic

- name: Replace main config file
  template:
    src: "prometheus.yml.j2"
    dest: "/etc/prometheus/prometheus.yml"
    force: true
  notify: restart prometheus

- name: Copy the prometheus systemd service file
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus
