---
# tasks file for wordpress
- name: Install epel repo
  ansible.builtin.yum:
    name:
      - epel-release
      - "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: latest

- name: Installing PHP 5.6
  shell: |
    yum-config-manager --enable remi-php56
    setenforce 0

- name: Install packages
  ansible.builtin.yum:
    name:
      - httpd
      - php
      - php-common
      - php-gd
      - php-mysql
      - php-xml
      - php-mbstring
      - git
    state: latest
    update_cache: yes

- name: Download WordPress tar.gz
  get_url:
    url: "https://wordpress.org/latest.tar.gz"
    dest: "/tmp/wordpress.tar.gz"
    mode: 0755
    timeout: 60
    force: true
    validate_certs: false
  register: get_wordpress
  until: get_wordpress is succeeded

- name: Create directrory for WordPress
  become: true
  file:
    state: directory
    path: "/var/www/wordpress"

- name: Extract Wordpress
  become: true
  unarchive:
    copy: false
    src: "/tmp/wordpress.tar.gz"
    dest: "/var/www/wordpress"
    owner: "apache"
    group: "apache"
    extra_opts: [--strip-components=1]

- name: Create log dir
  become: true
  file:
    path: "/var/www/wordpress/log"
    owner: "apache"
    group: "apache"
    state: directory

- name: Copy config file
  template:
    src: "wp-config.php.j2"
    dest: "/var/www/wordpress/wp-config.php"
    owner: "apache"
    group: "apache"

- name: Copy vhost file
  template:
    src: "wordpress.conf.j2"
    dest: "/etc/httpd/conf.d/wordpress.conf"
  notify: restart httpd

- name: Disable SELinux
  selinux:
    state: disabled
