---
# tasks file for mysql
- name: Install packages
  ansible.builtin.yum:
    name:
      - mariadb-server
      - MySQL-python
    state: latest
    update_cache: yes
    
- name: Copy the my.cnf file
  template:
    src: "my.cnf.j2"
    dest: "/etc/my.cnf"
  notify:
   - restart mysql

- name: Start the mysql
  service: 
    name: mariadb 
    state: started 
    enabled: yes 

- name: Update mysql root password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_pass }}"
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost

- name: Copy client conf file
  template:
    src: ".my.cnf.j2"
    dest: "~/.my.cnf"
    mode: 0600

- name: Create repl user
  ansible.builtin.mysql_user:
    name: "{{mysql_repl_user}}"
    host: "%"
    password: "{{mysql_repl_password}}"
    priv: "*.*:REPLICATION SLAVE"
    state: present
  when: mysql_repl_role == 'master'

- name: Check if slave is already configured for replication
  mysql_replication:
    mode: getslave
  ignore_errors: true
  register: slave
  when: mysql_repl_role == 'slave'

- name: Print the gateway for each host when defined
  ansible.builtin.debug:
    msg: "{{ slave }}"

- name: Get the current master servers replication status 
  mysql_replication:
    mode: getmaster 
  delegate_to: "db01.groshev.site"
  register: repl_stat
  when: (slave.Is_Slave is defined and not slave.Is_Slave) and mysql_repl_role == 'slave'

- name: Change the master in slave to start the replication
  mysql_replication:
    mode: changemaster
    master_host: "192.168.50.101"
    master_log_file: "{{ repl_stat.File }}"
    master_log_pos: "{{ repl_stat.Position }}"
    master_user: "{{ mysql_repl_user }}"
    master_password: "{{ mysql_repl_password }}"
  when: (slave.Is_Slave is defined and not slave.Is_Slave) and mysql_repl_role == 'slave'

- name: Create database
  ansible.builtin.mysql_db:
    name: wordpress
    state: present
    
- name: Create database user
  ansible.builtin.mysql_user:
    name: "{{mysql_user}}"
    host: "%"
    password: "{{mysql_password}}"
    priv: "wordpress.*:ALL"
    state: present
